const eventDummyData = [
  {
    id: 12,
    event_name: 'my event',
    creator: '12',
    likes: null,
    attendees: null,
    category: 'Sports',
    event_description: 'qwerty',
    fee: 100,
  },
  {
    id: 13,
    event_name: 'my event',
    creator: '12',
    likes: null,
    attendees: null,
    category: 'E-sports',
    event_description: 'qwerty',
    fee: 100,
  },
  {
    id: 14,
    event_name: 'my event',
    creator: '12',
    likes: null,
    attendees: null,
    category: 'Dance',
    event_description: 'qwerty',
    fee: 100,
  },
  {
    id: 15,
    event_name: 'my event',
    creator: '12',
    likes: null,
    attendees: null,
    category: 'Music',
    event_description: 'qwerty',
    fee: 100,
  },
  {
    id: 16,
    event_name: 'my event',
    creator: '12',
    likes: null,
    attendees: null,
    category: 'Arts_and_Craft',
    event_description: 'qwerty',
    fee: 100,
  },
]

export default eventDummyData
